### PR TITLE
Pass fee and crossover in execute to fix wrong transaction hash

### LINKED ISSUE #84: Current wallet-core creates transactions which cannot be verified on rusk side
At this particular code
https://github.com/dusk-network/wallet-core/blob/a925ead7fe13cb17d21f9fdd3af503f46d0bd641/src/tx.rs#L225-L232

In these lines the crossover is created again from the rng which yelds a different crossover and `Fee` stealth address which in case causes the proof to get corrupted.  

Either wallet-core needs to handle the stct proof generation (but it can't because it a network operation and we need to embed the proof in the `phoenix_core::transaction::Stake`

Or we pass the crossover rkyv serialized along with Fee rkyv serialized from the wallet-cli side. I did this locally and it solves the error and staking works.

### PR DESCRIPTION
**Pull request by Daksh14**
Use the same exact rng provided when generating output notes

Closes #84

### CODE REVIEW

File: src/types.rs [hunk 1]
```diff
@@ -31,15 +31,27 @@ pub struct BalanceResponse {
     #[doc = " Total computed balance"]
     pub value: u64,
 }
+#[doc = " The value of the Crossover and the blinder"]
+#[derive(Clone, PartialEq, Debug, Deserialize, Serialize)]
+pub struct Crossover {
```
Comment (Neotamandua) [inline src/types.rs:36]: This needs to be changed imo (as well for the crossover struct in tx.rs)
We should not have a crossover struct from Phoenix and then use that struct as a field in another struct (with additional fields) with the name crossover as well.

Comment (Daksh14) [reply src/types.rs:36]: I agree about that because its also super confusing. I had to set `use wallet_core::tx::Crossover as WasmCrossover`

File: src/utils.rs [hunk 2]
```diff
@@ -102,14 +102,9 @@ where
...
-    let mut hash = Sha256::new();
-
-    hash.update(seed);
-    hash.update(b"RNG");
-
-    let hash = hash.finalize().into();
-    ChaCha12Rng::from_seed(hash)
+/// We should keep this above 64 to be secure
+pub fn rng(seed: &[u8; 32]) -> ChaCha12Rng {
+    ChaCha12Rng::from_seed(*seed)
```
Comment (ureeves) [inline src/utils.rs:107]: Not sure I understand this comment, in conjunction with the change to a 256 bit seed. Also, if you're copying `*seed`, there's no reason to take it as reference.

**Review by ureeves — CHANGES_REQUESTED** [review]
Some things I'd like to see changed or addressed. I second @Neotamandua 's comment.

**Comment by Daksh14** [comment]
We will need to regenerate the wasm with this PR and then release @ureeves 

Ready for re-review

File: assets/dusk_wallet_core.wasm
[the remark this answers is not in the document]
Comment (ureeves) [reply assets/dusk_wallet_core.wasm:1]: There's still an artifact here. Do we really want to keep it?

File: src/types.rs [hunk 3]
```diff
@@ -31,15 +31,27 @@ pub struct BalanceResponse {
     #[doc = " Total computed balance"]
     pub value: u64,
 }
+#[doc = " The value of the Crossover and the blinder"]
+#[derive(Clone, PartialEq, Debug, Deserialize, Serialize)]
+pub struct CrossoverType {
```
Comment (ureeves) [inline src/types.rs:36]: I would suggest changing this for something more descriptive. Adding `Type` doesn't convey what it is. To help, here's some questions:

- What is this doing?
- What is it meant to do?

**Review by ureeves — CHANGES_REQUESTED** [review]

File: src/types.rs (hunk 3 above)
Comment (Daksh14) [reply src/types.rs:36]: It's the only way to transmit the crossover to the wasm side, that's why I put it to be "CrossoverType" since other types in the json schema have the suffix "Type". It has the blinder and the value that was used to construct the crossover and the phoenix_crossover itself

**Review by ureeves — APPROVED** [review]
@Daksh14 and I had a talk and decided that the `Type` suffix is definitely a *nit, and since the WASM payload was already there, we can deal with it in a subsequent PR. Since those were the only two objections, I'm approving. LGTM!

**Comment by Daksh14** [comment]
Follow up https://github.com/dusk-network/wallet-core/issues/94

File: assets/dusk_wallet_core.wasm
[the remark this answers is not in the document]
Comment (Daksh14) [reply assets/dusk_wallet_core.wasm:1]: We decided to keep it because one of the tests uses it
